# ------------------------------------
# SITE INFO SETTINGS

title: Open NC Collabrative
#subtitle: Pittsburgh's Code for America Brigade
email: info@open-nccollabrative.org
description: We are a collaborative group of Code for America volunteer brigades from North Carolina 
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://open-nc.github.io"
author:
street_address: 
city: 
state: NC
zip_code: 55555
country: United States of America
phone: (919) 555-5555

# Social media
github_url: https://github.com/opennccollab
twitter_url: https://twitter.com/opennccallab
meetup_url: https://www.meetup.com/opennccollab
slack_url: 
500px_url:
facebook_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:


# Logos
logo:
  banner: /assets/images/logos/banner.svg
  banner-white: /assets/images/logos/banner-white.svg
  banner-img: /assets/images/logos/banner.png
  icon-banner: /assets/images/logos/icon-banner.svg
  icon: /assets/images/logos/icon.svg

# ------------------------------------
# SITE CONFIG SETTINGS

sass:
    sass_dir: _sass
    
# post publication settings
future: false

# COLLECTIONS
collections:
  brigades:
  projects:
    output: true

# Build settings
markdown: kramdown
permalink: pretty
